import { BodyPartCatalog } from './data-models';

/**
 * Complete body part catalog with 30+ anatomical regions
 * Divided into front and back diagram regions
 */
export const bodyPartCatalog: BodyPartCatalog = {
  parts: {
    // Head & Neck
    head: {
      id: 'head',
      anatomicalName: 'Cabeza',
      location: 'front',
      side: 'center',
      category: 'head',
    },
    neck: {
      id: 'neck',
      anatomicalName: 'Cuello',
      location: 'front',
      side: 'center',
      category: 'neck',
    },

    // Shoulders
    left_shoulder: {
      id: 'left_shoulder',
      anatomicalName: 'Hombro Izquierdo',
      abbreviation: 'Hombro Izq.',
      location: 'front',
      side: 'left',
      category: 'shoulders',
    },
    right_shoulder: {
      id: 'right_shoulder',
      anatomicalName: 'Hombro Derecho',
      abbreviation: 'Hombro Der.',
      location: 'front',
      side: 'right',
      category: 'shoulders',
    },
    left_deltoid: {
      id: 'left_deltoid',
      anatomicalName: 'Deltoides Izquierdo',
      abbreviation: 'Delt. Izq.',
      location: 'front',
      side: 'left',
      category: 'shoulders',
    },
    right_deltoid: {
      id: 'right_deltoid',
      anatomicalName: 'Deltoides Derecho',
      abbreviation: 'Delt. Der.',
      location: 'front',
      side: 'right',
      category: 'shoulders',
    },

    // Arms
    left_bicep: {
      id: 'left_bicep',
      anatomicalName: 'Bíceps Izquierdo',
      abbreviation: 'Bíceps Izq.',
      location: 'front',
      side: 'left',
      category: 'arms',
    },
    right_bicep: {
      id: 'right_bicep',
      anatomicalName: 'Bíceps Derecho',
      abbreviation: 'Bíceps Der.',
      location: 'front',
      side: 'right',
      category: 'arms',
    },
    left_tricep: {
      id: 'left_tricep',
      anatomicalName: 'Tríceps Izquierdo',
      abbreviation: 'Tríceps Izq.',
      location: 'back',
      side: 'left',
      category: 'arms',
    },
    right_tricep: {
      id: 'right_tricep',
      anatomicalName: 'Tríceps Derecho',
      abbreviation: 'Tríceps Der.',
      location: 'back',
      side: 'right',
      category: 'arms',
    },

    // Forearms
    left_forearm: {
      id: 'left_forearm',
      anatomicalName: 'Antebrazo Izquierdo',
      abbreviation: 'Antebr. Izq.',
      location: 'front',
      side: 'left',
      category: 'forearms',
    },
    right_forearm: {
      id: 'right_forearm',
      anatomicalName: 'Antebrazo Derecho',
      abbreviation: 'Antebr. Der.',
      location: 'front',
      side: 'right',
      category: 'forearms',
    },

    // Hands
    left_hand: {
      id: 'left_hand',
      anatomicalName: 'Mano Izquierda',
      abbreviation: 'Mano Izq.',
      location: 'front',
      side: 'left',
      category: 'hands',
    },
    right_hand: {
      id: 'right_hand',
      anatomicalName: 'Mano Derecha',
      abbreviation: 'Mano Der.',
      location: 'front',
      side: 'right',
      category: 'hands',
    },

    // Chest & Abdomen
    chest: {
      id: 'chest',
      anatomicalName: 'Pecho',
      location: 'front',
      side: 'center',
      category: 'chest',
    },
    left_breast: {
      id: 'left_breast',
      anatomicalName: 'Seno Izquierdo',
      abbreviation: 'Seno Izq.',
      location: 'front',
      side: 'left',
      category: 'chest',
    },
    right_breast: {
      id: 'right_breast',
      anatomicalName: 'Seno Derecho',
      abbreviation: 'Seno Der.',
      location: 'front',
      side: 'right',
      category: 'chest',
    },
    abdomen: {
      id: 'abdomen',
      anatomicalName: 'Abdomen',
      location: 'front',
      side: 'center',
      category: 'abdomen',
    },

    // Back
    upper_back: {
      id: 'upper_back',
      anatomicalName: 'Espalda Superior',
      location: 'back',
      side: 'center',
      category: 'back',
    },
    mid_back: {
      id: 'mid_back',
      anatomicalName: 'Espalda Media',
      location: 'back',
      side: 'center',
      category: 'back',
    },
    lower_back: {
      id: 'lower_back',
      anatomicalName: 'Espalda Baja',
      location: 'back',
      side: 'center',
      category: 'lower_back',
    },

    // Hips & Pelvis
    left_hip: {
      id: 'left_hip',
      anatomicalName: 'Cadera Izquierda',
      abbreviation: 'Cadera Izq.',
      location: 'front',
      side: 'left',
      category: 'pelvis',
    },
    right_hip: {
      id: 'right_hip',
      anatomicalName: 'Cadera Derecha',
      abbreviation: 'Cadera Der.',
      location: 'front',
      side: 'right',
      category: 'pelvis',
    },
    left_glute: {
      id: 'left_glute',
      anatomicalName: 'Glúteo Izquierdo',
      abbreviation: 'Glúteo Izq.',
      location: 'back',
      side: 'left',
      category: 'pelvis',
    },
    right_glute: {
      id: 'right_glute',
      anatomicalName: 'Glúteo Derecho',
      abbreviation: 'Glúteo Der.',
      location: 'back',
      side: 'right',
      category: 'pelvis',
    },

    // Thighs
    left_thigh: {
      id: 'left_thigh',
      anatomicalName: 'Muslo Izquierdo',
      abbreviation: 'Muslo Izq.',
      location: 'front',
      side: 'left',
      category: 'thighs',
    },
    right_thigh: {
      id: 'right_thigh',
      anatomicalName: 'Muslo Derecho',
      abbreviation: 'Muslo Der.',
      location: 'front',
      side: 'right',
      category: 'thighs',
    },

    // Knees
    left_knee: {
      id: 'left_knee',
      anatomicalName: 'Rodilla Izquierda',
      abbreviation: 'Rodilla Izq.',
      location: 'front',
      side: 'left',
      category: 'knees',
    },
    right_knee: {
      id: 'right_knee',
      anatomicalName: 'Rodilla Derecha',
      abbreviation: 'Rodilla Der.',
      location: 'front',
      side: 'right',
      category: 'knees',
    },

    // Shins
    left_shin: {
      id: 'left_shin',
      anatomicalName: 'Tibia Izquierda',
      abbreviation: 'Tibia Izq.',
      location: 'front',
      side: 'left',
      category: 'shins',
    },
    right_shin: {
      id: 'right_shin',
      anatomicalName: 'Tibia Derecha',
      abbreviation: 'Tibia Der.',
      location: 'front',
      side: 'right',
      category: 'shins',
    },

    // Feet
    left_foot: {
      id: 'left_foot',
      anatomicalName: 'Pie Izquierdo',
      abbreviation: 'Pie Izq.',
      location: 'front',
      side: 'left',
      category: 'feet',
    },
    right_foot: {
      id: 'right_foot',
      anatomicalName: 'Pie Derecho',
      abbreviation: 'Pie Der.',
      location: 'front',
      side: 'right',
      category: 'feet',
    },
  },

  frontDiagram: [
    'head',
    'neck',
    'left_shoulder',
    'right_shoulder',
    'left_deltoid',
    'right_deltoid',
    'left_bicep',
    'right_bicep',
    'left_forearm',
    'right_forearm',
    'left_hand',
    'right_hand',
    'chest',
    'left_breast',
    'right_breast',
    'abdomen',
    'left_hip',
    'right_hip',
    'left_thigh',
    'right_thigh',
    'left_knee',
    'right_knee',
    'left_shin',
    'right_shin',
    'left_foot',
    'right_foot',
  ],

  backDiagram: [
    'neck',
    'left_shoulder',
    'right_shoulder',
    'left_deltoid',
    'right_deltoid',
    'left_tricep',
    'right_tricep',
    'left_forearm',
    'right_forearm',
    'left_hand',
    'right_hand',
    'upper_back',
    'mid_back',
    'lower_back',
    'left_glute',
    'right_glute',
    'left_thigh',
    'right_thigh',
    'left_knee',
    'right_knee',
    'left_shin',
    'right_shin',
    'left_foot',
    'right_foot',
  ],

  categories: [
    'head',
    'neck',
    'shoulders',
    'arms',
    'forearms',
    'hands',
    'chest',
    'abdomen',
    'back',
    'lower_back',
    'pelvis',
    'thighs',
    'knees',
    'shins',
    'feet',
  ],

  version: '1.0',
};
